title: Oluwadamilola Popoola (Dami)
#logo:

description:
  <p align="center">
  <a href="">Resume</a> |
  <a href="https://www.linkedin.com/in/damipopoola/">LinkedIn</a> |
  <a href="">Github</a> |
  </p>

  <p align="justify">
  My name is Oluwadamilola Popoola, also known as Dami.
  I am a passionate freelancing Data Scientist with coding experience in Front-end Development.
  <br><br>
  As a proficient front-end developer, my foundation lies in crafting immersive user experiences through HTML, CSS, and other Web 2.0 technologies. 
  This skill set enables me to create visually appealing and responsive interfaces that resonate with modern design principles.
  However, my proficiency extends beyond the conventional boundaries of front-end development. 
  With a keen interest in Data science, I have also integrated machine learning and AI into my skillset. 
  In essence, my skill set not only caters to the aesthetic and functional aspects of the digital realm but also embraces the transformative potential embedded in the intelligent evolution of the web.
  Other passions of mine include 

show_downloads: true
theme: jekyll-theme-minimal
