title: Oluwadamilola Popoola (Dami)
logo: /assets/damipotraitpic.png 
Description: My name is Oluwadamilola Popoola, also known as Dami. I am a passionate Data Scientist with coding experience in Front-end Development.
Other passions of mine include 
show_downloads: true
theme: jekyll-theme-minimal
