title: <p align="center"> Oluwadamilola Popoola (Dami) </p>
logo: "https://raw.githubusercontent.com/damipop7/Dami-Portfolio/main/Assets/Images/IMG_7879 copy.heic" 

description:
  <p align="center">
  <a href="">Resume</a> |
  <a href="https://www.linkedin.com/in/damipopoola/">LinkedIn</a> |
  <a href="">Github</a> |
  </p>

  <p align="justify">
  My name is Oluwadamilola Popoola, also known as Dami.
  I am a passionate freelancing Data Scientist with coding experience in Front-end Development.

show_downloads: true
theme: jekyll-theme-minimal
