title: <p align="center"> Oluwadamilola Popoola (Dami) </p>
logo: "https://raw.githubusercontent.com/damipop7/Dami-Portfolio/main/Assets/Images/damipotraitpic.pngf" 

#"/Images/IMG_7879.pdf?raw=true"

description:
  <p align="center">
  <a href="Assets/DSDamiPopoolaResume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/damipopoola/">LinkedIn</a> |
  <a href="https://github.com/damipop7">Github</a> 
  </p>

  <p align="justify">
  My name is Oluwadamilola Popoola, also known as Dami.
  I am a passionate freelancing Data Scientist with coding experience in Front-end Development.

show_downloads: true
theme: jekyll-theme-minimal
