title: <p align="center"> Oluwadamilola Popoola (Dami) </p>
logo: "/Images/IMG_7879.heic" 

description:
  <p align="center">
  <a href="">Resume</a> |
  <a href="https://www.linkedin.com/in/damipopoola/">LinkedIn</a> |
  <a href="">Github</a> |
  </p>

  <p align="justify">
  My name is Oluwadamilola Popoola, also known as Dami.
  I am a passionate freelancing Data Scientist with coding experience in Front-end Development.
  <br><br>
  As a proficient Data scientist, my foundation lies in integrating machine learning and Artificial Intelligence, using them to solve day-to-day problems and provide insights. 
  However, my proficiency extends beyond the conventional boundaries of Data science. 
  With a keen interest in front-end development, I have also crafted immersive user experiences through HTML, CSS, and so on. 

show_downloads: true
theme: jekyll-theme-minimal
