title: Oluwadamilola Popoola (Dami)
#logo:

description:
  <p align="center">
  <a href="">Resume</a> |
  <a href="https://www.linkedin.com/in/damipopoola/">LinkedIn</a> |
  <a href="">Github</a> |
  </p>

  <p align="justify">
  My name is Oluwadamilola Popoola, also known as Dami.
  I am a passionate freelancing Data Scientist with coding experience in Front-end Development.
  <br><br>
  As a proficient front-end developer, my foundation lies in crafting immersive user experiences through HTML, CSS, and so on. 
  However, my proficiency extends beyond the conventional boundaries of front-end development. 
  With a keen interest in Data science, I have also integrated machine learning and AI into my skillset. 

show_downloads: true
theme: jekyll-theme-minimal
